[package]
name = "imgdd"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "cargo"] }
anyhow = "1.0.95"
env_logger = "0.11.6"
log = "0.4.22"
image = "0.25.5"
ndarray = "0.16.1"
rayon = "1.10.0"
dashmap = "6.1.0"
crossbeam = "0.8.4"
lazy_static = "1.5.0"
walkdir = "2.3"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "dedupe_bench"
path = "benches/dedupe_bench.rs"
harness = false
