ignore:
  - "crates/imgddpy/**/*" # ignore pyo3 lib in favor of python integration testing / benchmarking
  - "crates/imgddcore/benches/**/*"
  - "crates/imgddcore/tests/**/*"
  - "crates/imgdd/benches/**/*"
  - "crates/imgdd/tests/**/*"
