name: CodSpeed Benchmarks

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_call:
        secrets:
            codspeed_token:
                required: true
        inputs:
            branch:
                required: false
                type: string
                default: "main"
    workflow_dispatch:
        inputs:
            dry-run:
                description: Dry run
                type: boolean
                default: false
  

jobs:
  build-and-test:
    name: Build and Benchmark
    runs-on: codspeed-macro
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd crates/python/
          pip install .[test]

      - name: Run benchmark tests
        uses: CodSpeedHQ/action@v3
        if: ${{ !inputs.dry-run }}
        with:
          working-directory: crates/python
          run: pytest -m benchmark --codspeed -v
          token: ${{ secrets.CODSPEED_TOKEN }}
