name: CodSpeed Benchmarks

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_call:
        secrets:
            codspeed_token:
                required: true
        inputs:
            branch:
                required: false
                type: string
                default: "main"
    workflow_dispatch:
  
jobs:
  python:
    name: Python Build and Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd crates/python/
          pip install .[test]

      - name: Run benchmark tests
        uses: CodSpeedHQ/action@v3
        with:
          working-directory: crates/python
          run: pytest -m benchmark --codspeed -v
          token: ${{ secrets.CODSPEED_TOKEN }}

  rust:
    name: Rust Build and Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo codspeed build --features benchmark

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: cargo codspeed run
          token: ${{ secrets.CODSPEED_TOKEN }}