name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    secrets:
      codecov_token:
        required: true
    inputs:
      branch:
        required: false
        type: string
        default: "main"
  workflow_dispatch:
  
jobs:
  build:
    name: Build and Report Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Python Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-dev python3-pip python3-venv

    - name: Set Up Python Linking
      run: |
        mkdir -p .cargo
        PYTHON_VERSION=$(python3 --version | awk '{print $2}' | cut -d '.' -f 1,2)
        PYTHON_LIB_PATH=$(python3-config --prefix)/lib
        echo "[build]" >> .cargo/config.toml
        echo "rustflags = [\"-L$PYTHON_LIB_PATH\", \"-lpython${PYTHON_VERSION}\"]" >> .cargo/config.toml
      shell: bash

    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run Tests and Generate Coverage Report
      run: cargo tarpaulin --out Lcov --features testing
      env:
        CARGO_INCREMENTAL: '0'

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./tarpaulin-report.lcov
        verbose: true
        fail_ci_if_error: true
