name: Publish Python Documentation

on:
  workflow_dispatch:
  # test manual publish from tag
  # push:
  #   tags: "py-v*"
  #   tags: "py-v[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  coverage:
    uses: ./.github/workflows/coverage.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    uses: ./.github/workflows/integration.yml
    with:
      branch: ${{ github.ref_name }}

  publish-docs:
    needs: [coverage, integration-tests]
    name: Release docs page
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Dependencies
        run: |
          cd crates/imgddpy/
          pip install .[dev]
      
      - name: Build and Deploy Documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          # Fetch the gh-pages branch
          git fetch origin gh-pages

          # Extract version from the tag (py-v*)
          VERSION=$(echo "py-v0.1.0-stage" | sed 's/^py-v//')
          echo "VERSION extracted: $VERSION"

          # Build and deploy using mike
          cd crates/imgddpy/
          mike deploy --push --branch gh-pages "$VERSION" latest
          mike set-default --push --branch gh-pages latest