name: Python Integration Tests


on:
    push:
      branches: [ "main", "stage" ]
    pull_request:
      branches: [ "main" ]

# on:
#     workflow_call:
#       inputs:
#         branch:
#           required: false
#           type: string
#           default: "main"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v3
    #   - name: Set up Python and tox
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.x'

    #   - name: Set up Python 3.8
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: 3.8

    #   - name: Set up Python 3.9
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd crates/python/
          pip install .[test]

      - name: Run tests
        run: |
            cd crates/python/
            tox --parallel auto
