name: Publish Python Package

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Repo Branch
        required: true
        default: 'main'
        type: choice
        options:
        - main
        - stage
      dry-run:
        description: Dry run
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  build-and-publish:
    name: Build and Publish Python Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha || 'main' }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin
        run: pip install maturin

      - name: Build Python wheels
        run: |
          maturin build --release --manifest-path crates/python/Cargo.toml
          ls -l target/wheels

      - name: Build Python source distributions
        run: |
          maturin sdist --manifest-path crates/python/Cargo.toml
          ls -l dist

      - name: Dry run or Publish
        if: ${{ inputs.dry-run }}
        run: |
          echo "Dry run: Skipping upload to PyPI."

      - name: Publish to PyPI
        if: ${{ !inputs.dry-run }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
