name: Publish Rust Crate

on:
  workflow_dispatch:
    inputs:
      crate:
        description: Select the crate to publish
        type: choice
        options:
          - imgdd
          - imgddcore
        default: imgddcore
      toolchain:
        description: Select the toolchain to build with
        type: choice
        options:
          - stable
          - beta
          - nightly
        default: stable
      dry-run:
        description: Dry run (skip publish)
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.crate }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-version:
    name: Validate Branch or Tag
    runs-on: ubuntu-latest
    steps:
      - name: Validate Version Pattern
        id: validate
        run: |
          echo "Checking branch or tag: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" =~ ^rs-v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Valid version pattern."
          else
            echo "❌ Version pattern mismatch! Expected: rs-v[0-9]+\.[0-9]+\.[0-9]+"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Version Match
        run: |
          cd crates/${{ inputs.crate }}
          VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "${{ inputs.crate }}") | .version')
          EXPECTED_VERSION="rs-v$VERSION"
          CURRENT_BRANCH="${{ github.ref_name }}"

          if [ "$EXPECTED_VERSION" = "$CURRENT_BRANCH" ]; then
            echo "✅ Version matches the branch/tag: $CURRENT_BRANCH"
          else
            echo "❌ Version mismatch! Expected: $EXPECTED_VERSION, Found: $CURRENT_BRANCH"
            exit 1
          fi

  coverage:
    uses: ./.github/workflows/coverage.yml
    needs: validate-version
    with:
      branch: ${{ github.ref_name }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    needs: validate-version
    uses: ./.github/workflows/integration.yml
    with:
      branch: ${{ github.ref_name }}

  dry-run:
    needs: [coverage, integration-tests]
    name: Dry Run
    runs-on: ubuntu-latest
    if: ${{ inputs.dry-run }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          override: true

      - name: Dry Run Cargo Release Publish
        run: |-
          cargo publish \
            --manifest-path crates/${{ inputs.crate }}/Cargo.toml \
            --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish:
    needs: [coverage, integration-tests]
    name: Publish ${{ inputs.crate }} Crate
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ inputs.toolchain }}
          override: true

      - name: Check Version
        run: |
          cd crates/${{ inputs.crate }}
          VERSION=$(toml get Cargo.toml package.version)
          test "rs-v$VERSION" = "${{ github.ref_name }}"

      - name: Cargo Release Publish
        run: |-
          cargo publish \
            --manifest-path crates/${{ inputs.crate }}/Cargo.toml
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
