name: Publish Python Package

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run (skip publish)
        type: boolean
        default: false
        

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.9'
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10

jobs:
  benchmark:
    uses: ./.github/workflows/benchmark.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      codspeed_token: ${{ secrets.CODSPEED_TOKEN }}

  coverage:
    uses: ./.github/workflows/coverage.yml
    with:
      branch: ${{ github.ref_name }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  integration-tests:
    uses: ./.github/workflows/integration.yml
    with:
      branch: ${{ github.ref_name }}

  create-sdist:
    needs: [benchmark, coverage, integration-tests]
    name: Build and Test Source Distributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install maturin
        run: pip install maturin

      - name: Build source distribution
        run: |
          maturin sdist --manifest-path crates/imgddpy/Cargo.toml
          ls -l target/wheels/

      - name: Test source distribution
        run: |
          pip install --force-reinstall --verbose target/wheels/*.tar.gz
          python -c 'import imgdd'  # Replace 'imgdd' with the correct import

      - name: Upload sdist artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdist-imgdd
          path: target/wheels/*.tar.gz

  build-wheels:
    needs: [benchmark, coverage, integration-tests]
    name: Build Wheels
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux (x64 and ARM)
          - os: ubuntu-latest
            compatibility: manylinux_2_34

          - os: ubuntu-22.04-arm
            compatibility: manylinux_2_34

          - os: ubuntu-latest
            compatibility: musllinux_1_2

          - os: ubuntu-22.04-arm
            compatibility: musllinux_1_2

          # macOS (x64 and ARM)
          - os: macos-latest # ARM
            compatibility: none

          - os: macos-13 # x64
            compatibility: none

          # Windows (x64 only)
          - os: windows-latest
            compatibility: none

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install maturin
        run: |
          if [ "${{ matrix.compatibility }}" == "musllinux_1_2" ]; then
            pip install maturin[patchelf]
          else
            pip install maturin
          fi

      - name: Prepare Rust target (Linux x64 only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          if [ "${{ matrix.compatibility }}" == "musllinux_1_2" ]; then
            rustup target add x86_64-unknown-linux-musl
          elif [ "${{ matrix.compatibility }}" == "manylinux_2_34" ]; then
            rustup target add x86_64-unknown-linux-gnu
          fi

      - name: Build wheel
        run: |
          if [[ "${{ matrix.compatibility }}" == "none" ]]; then
            maturin build --release --manifest-path crates/imgddpy/Cargo.toml
          else
            maturin build --release --manifest-path crates/imgddpy/Cargo.toml --compatibility ${{ matrix.compatibility }}
          fi
          ls -l target/wheels/

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          path: target/wheels/*.whl
        

  publish-to-pypi:
    needs: [create-sdist, build-wheels]
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    if: ${{ !inputs.dry-run }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  dry-run-check:
    needs: [create-sdist, build-wheels]
    name: Dry Run
    runs-on: ubuntu-latest
    if: ${{ inputs.dry-run }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Dry run output
        run: |
          echo "Dry run completed. Artifacts are built and available:"
          ls -l dist/
