name: Publish Rust Crate

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean
        default: false
    
jobs:
  integration-tests:
    uses: ./.github/workflows/integration.yml
    with:
      branch: ${{ github.ref_name }}

  build:
    needs: integration-tests
    runs-on: ubuntu-latest
    

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Dry run or Publish
      if: ${{ inputs.dry-run }}
      run: |
        echo "Dry run: Skipping upload to Crate.io."

    # UPDATE COPIED PYPI BLOCK
    # - name: Publish to PyPi
    #   if: ${{ !inputs.dry-run }}
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
