name: Rust CI with Coverage

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Rust toolchain
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    # Build the project
    - name: Build
      run: cargo build --verbose

    # Run tests with profiling
    - name: Run Tests with Profiling
      run: cargo test --verbose
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

    # Generate coverage report using grcov
    - name: Generate Coverage Report
      uses: actions-rs/grcov@v0.1

      
    # Upload coverage to Codecov
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./lcov.info
        flags: unittests
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
